[options]
addons_path = /home/hiephv/PycharmProjects/Odoo18/enterprise
db_host = localhost
db_port = 5432
db_user = odoo18
db_password = odoo18
db_name = False
db_maxconn = 64
http_interface = 0.0.0.0
http_port = 1818
gevent_port = 1819
admin_passwd = 1
log_level = info
logfile = False
list_db = True
without_demo = False
limit_time_cpu = 60
limit_time_real = 120
max_cron_threads = 2
data_dir = ~/.local/share/Odoo18
server_wide_modules = base,web

# Disable GeoIP to fix authentication error
geoip_city_db = False
geoip_country_db = False

